require: rubocop-rails

AllCops:
  NewCops: disable
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'

Metrics/AbcSize:
  Max: 20

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/devise.rb'

Metrics/BlockLength:
  Exclude:
    - config/environments/production.rb
    - config/initializers/rails_admin.rb

Metrics/MethodLength:
  Max: 15

Rails/Output:
  Exclude:
    - 'config/unicorn.rb'

Style/Documentation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false
