AllCops:
  RunRailsCops: true
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'

Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/devise.rb'

Metrics/MethodLength:
  Max: 15

Rails/Output:
  Exclude:
    - 'config/unicorn.rb'

Style/Documentation:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false
